### ISSUE TITLE
`sst dev` does not pick up the runtime from Code

### ISSUE THREAD

**Issue by jolo-dev** [serverless-stack/sst#3174]
As my node version manager, I use [fnm](https://github.com/Schniz/fnm).
It defaults to node 18. I started my machine with node 19.
I have several Lambdas and I use the `runtime` option (see below)

```ts
new Function(scope, 'foo', {
        runtime: "nodejs18.x",
        handler: `packages/functions/src/foo.handler`
   })
```

However, running `sst dev` deploys Lambdas with `nodejs16.x`. I get that it tries to mimic my local setup (unfortunately, wrongly), but it should have picked the runtime from the code.
When running `sst deploy`, the Lambdas are deployed with the runtime `nodejs18.x` correctly.

Ideally, sst should default to node 18 or it should simply pickup the runtime from the code.

---

https://discord.com/channels/983865673656705025/1007139657324187729/1135968923775422505

**Comment by boringContributor** [comment]
The lambda live uses Node 16 you can't change that.

**Comment by jayair** [comment]
The function that's deployed is just to proxy calls to your local. Is there a reason why you want it on 18. I imagine we'll update it at some point.

**Comment by jolo-dev** [comment]
Yes, but on my local is nodev18.
The reason, we implemented SST in our company but have some compliance and auditing for our AWS account. They want me to not use below 18.
And another reason node16 reaches the EOL and next month will have no support: https://endoflife.date/nodejs

**Comment by jayair** [comment]
Ah that makes sense. Let me tell the team about it.

**Comment by thdxr** [comment]
this is fixed in latest

**Comment by iDVB** [comment]
Still getting this:
`Error: nodejs18.x runtime is unsupported`

sst@2.24.24
